// db/seed.ts - Datos de ejemplo para desarrollo
import { db, Lugares } from 'astro:db';

export default async function seed() {
  await db.insert(Lugares).values([
    {
      id: 1,
      nombre: 'Hotel Los Andes Accesible',
      descripcion: 'Hotel boutique con habitaciones completamente adaptadas para personas con discapacidad. Cuenta con certificación Yapaykuy.',
      direccion: 'Av. La Marina 2355',
      ciudad: 'Lima',
      region: 'Lima',
      tipo: 'hotel',
      certificadoYapaykuy: true,
      rampaAcceso: true,
      banioAdaptado: true,
      estacionamientoAccesible: true,
      senaleticaBraille: true,
      audioguia: false,
      personalCapacitado: true,
      telefono: '01-234-5678',
      email: '[email protected]',
      sitioWeb: 'https://ejemplo.com',
      imagenUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500',
    },
    {
      id: 2,
      nombre: 'Restaurante El Mirador Inclusivo',
      descripcion: 'Restaurante de comida peruana con menú en braille y personal capacitado en lenguaje de señas.',
      direccion: 'Calle Las Palmeras 456',
      ciudad: 'Arequipa',
      region: 'Arequipa',
      tipo: 'restaurante',
      certificadoYapaykuy: true,
      rampaAcceso: true,
      banioAdaptado: true,
      estacionamientoAccesible: true,
      senaleticaBraille: true,
      audioguia: false,
      personalCapacitado: true,
      telefono: '054-123-456',
      email: '[email protected]',
      sitioWeb: 'https://ejemplo.com',
      imagenUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500',
    },
    {
      id: 3,
      nombre: 'Centro Comercial Plaza Inclusión',
      descripcion: 'Moderno centro comercial con todas las facilidades de accesibilidad.',
      direccion: 'Av. Javier Prado Este 890',
      ciudad: 'Lima',
      region: 'Lima',
      tipo: 'comercio',
      certificadoYapaykuy: false,
      rampaAcceso: true,
      banioAdaptado: true,
      estacionamientoAccesible: true,
      senaleticaBraille: false,
      audioguia: false,
      personalCapacitado: true,
      telefono: '01-987-6543',
      email: '[email protected]',
      sitioWeb: 'https://ejemplo.com',
      imagenUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=500',
    },
    {
      id: 4,
      nombre: 'Museo de Arte Contemporáneo Accesible',
      descripcion: 'Museo con tours guiados adaptados, audioguías y exposiciones táctiles.',
      direccion: 'Av. Grau 1234',
      ciudad: 'Cusco',
      region: 'Cusco',
      tipo: 'cultura',
      certificadoYapaykuy: true,
      rampaAcceso: true,
      banioAdaptado: true,
      estacionamientoAccesible: true,
      senaleticaBraille: true,
      audioguia: true,
      personalCapacitado: true,
      telefono: '084-456-789',
      email: '[email protected]',
      sitioWeb: 'https://ejemplo.com',
      imagenUrl: 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=500',
    },
  ]);
}